Sprint 6 solution
gor1sher/java-kanban pull request #1
Opened 2024-05-15 18:18 UTC by gor1sher

Добавлены тесты, также реализован двусвязный список

2024-05-16 10:52 UTC, TomattmanYandex requested changes
Привет, поф функционалу вопросы минимальные, больше по именам и модификаторам доступа, а вот тестов для менеджера истории не хватает

2024-05-16 10:52 UTC, TomattmanYandex commented on src/service/InMemoryHistoryManager.java
> +    public class Node {
лучше сделать этот класс приватным, ну или придётся делать приватными поля и писать геттеры сеттеры на поля

2024-05-16 10:52 UTC, TomattmanYandex commented on src/service/InMemoryHistoryManager.java
> +    class List {
Когда я в коде в начале класса увидел что там переменная типа List то подумал, что задание вообще не выполнено, не стоит делать такие имена которые будет путать
Лучше бы дать ему имя например CustomLinkedList

2024-05-16 10:52 UTC, TomattmanYandex commented on src/service/InMemoryHistoryManager.java
> +    class List {
и то же сделать приватным

2024-05-16 10:52 UTC, TomattmanYandex commented on src/service/InMemoryHistoryManager.java
> +        void remove(Node node) {
кажется логику этого метода можно немного упростить, но не обязательно

2024-05-17 07:24 UTC, TomattmanYandex requested changes
Привет, по тестом еще надо доработать

2024-05-17 07:24 UTC, TomattmanYandex commented on test/InMemoryHistoryManagerTest.java
> +        System.out.println(list);
зачем тут вывод с консоль чего то?
Все, это уже  реальный проект, в них обычно выводы в консоль не добавляют

2024-05-17 07:24 UTC, TomattmanYandex commented on test/InMemoryHistoryManagerTest.java
> +    InMemoryTaskManager inMemoryTaskManager = new InMemoryTaskManager(new InMemoryHistoryManager());
зачем тут таск менеджер, менеджер истории никак от него не зависит
здесь мы проверяем сам менеджер истории а не его интеграцию с таск менеджером (их интеграцию можно проверить в тесте таск менедежера, что после getById, getHistory возвращает этот обьект)

2024-05-17 07:24 UTC, TomattmanYandex commented on test/InMemoryHistoryManagerTest.java
> +    InMemoryTaskManager inMemoryTaskManager = new InMemoryTaskManager(new InMemoryHistoryManager());
тесты надо переписать исходя из этого

2024-05-17 07:24 UTC, TomattmanYandex commented on test/InMemoryHistoryManagerTest.java
> +    InMemoryTaskManager inMemoryTaskManager = new InMemoryTaskManager(new InMemoryHistoryManager());
кстати я посмотрел что там есть тесты на удаления, их тоже следует в таком виде перенести в тест таск менеджера

2024-05-17 07:24 UTC, TomattmanYandex commented on test/InMemoryHistoryManagerTest.java
> +import model.Epic;
обычно тесты находятся в точно таком же пакете как и тестируемый класс
следовательно если тестируем класс service.InMemoryHistoryManager;
значит его тест должен быть в папке test в пакете service

2024-05-17 07:24 UTC, TomattmanYandex commented on test/InMemoryTaskManagerTest.java
> +    void getDefault_сreationTwoObjects_InMemoryTaskManager() {
первая часть, это имя тестируемого метода
также, обычно тестируют каждый метод отдельным тестом
а вообще следует создать методы 
getTaskById_returnObject
getTaskById_throw[Тип_ошибки]_objectNotFound (ну или getTaskById_returnNull_objectNotFound в зависимости от реализации)
getTaskById_addTaskToHIstory_objectFound

2024-05-17 07:24 UTC, TomattmanYandex commented on test/InMemoryTaskManagerTest.java
> +    void getDefault_сreationTwoObjects_InMemoryTaskManager() {
а еще обычно не каждый публичный метод в сервисе, есть тест, и даже не один,а по тесту на каждый случай, в текущей работе можно все не дописывать, это будет чуть дальше, сейчас стоит поправить то что уже есть

2024-05-17 09:17 UTC, gor1sher commented on test/InMemoryHistoryManagerTest.java
> +        System.out.println(list);
Я делал проверку, забыл убрать

2024-05-17 17:39 UTC, TomattmanYandex approved these changes
Принято

2024-05-29 15:02 UTC, merged